create extension if not exists pgcrypto;

create table if not exists public.youtube_keyword_master_videos (
  video_id text primary key,
  category_key text not null,
  youtube_category_id text not null,
  channel_id text not null,
  channel_title text not null,
  title text not null,
  description text not null default '',
  thumbnail_url text not null,
  duration_iso8601 text not null,
  duration_seconds integer not null default 0,
  duration_display text not null,
  published_at timestamptz not null,
  youtube_url text not null,
  tags text[] not null default '{}',
  updated_at timestamptz not null default now()
);

create table if not exists public.youtube_keyword_master_video_snapshots (
  id bigint generated by default as identity primary key,
  video_id text not null references public.youtube_keyword_master_videos(video_id) on delete cascade,
  category_key text not null,
  snapshot_date date not null,
  rank smallint not null,
  view_count bigint not null default 0,
  like_count bigint not null default 0,
  comment_count bigint not null default 0,
  collected_at timestamptz not null default now(),
  unique (video_id, category_key, snapshot_date)
);

create index if not exists youtube_keyword_master_snapshots_date_idx
  on public.youtube_keyword_master_video_snapshots (snapshot_date desc, category_key, rank);

create table if not exists public.youtube_keyword_master_analysis_results (
  id uuid primary key default gen_random_uuid(),
  video_id text not null unique references public.youtube_keyword_master_videos(video_id) on delete cascade,
  channel_title text not null,
  title text not null,
  youtube_url text not null,
  thumbnail_url text not null,
  duration_display text not null,
  duration_seconds integer not null default 0,
  published_at timestamptz not null,
  view_count bigint not null default 0,
  like_count bigint not null default 0,
  comment_count bigint not null default 0,
  hashtags text[] not null default '{}',
  top_comments jsonb not null default '[]'::jsonb,
  transcript text,
  analyzed_at timestamptz not null default now()
);

create table if not exists public.youtube_keyword_master_collection_runs (
  id uuid primary key default gen_random_uuid(),
  collection_date date not null,
  status text not null check (status in ('running', 'completed', 'partial', 'failed')),
  video_count integer not null default 0,
  error_message text,
  started_at timestamptz not null default now(),
  completed_at timestamptz
);

create or replace function public.youtube_keyword_master_set_updated_at()
returns trigger
language plpgsql
as $$
begin
  new.updated_at = now();
  return new;
end;
$$;

drop trigger if exists youtube_keyword_master_videos_updated_at on public.youtube_keyword_master_videos;
create trigger youtube_keyword_master_videos_updated_at
before update on public.youtube_keyword_master_videos
for each row execute function public.youtube_keyword_master_set_updated_at();

create or replace view public.youtube_keyword_master_trending_videos
with (security_invoker = true)
as
with ordered as (
  select
    snapshot.*,
    row_number() over (
      partition by snapshot.video_id, snapshot.category_key
      order by snapshot.snapshot_date desc, snapshot.collected_at desc
    ) as snapshot_number
  from public.youtube_keyword_master_video_snapshots snapshot
), current_snapshot as (
  select * from ordered where snapshot_number = 1
), previous_snapshot as (
  select * from ordered where snapshot_number = 2
)
select
  video.video_id,
  current_snapshot.category_key,
  video.youtube_category_id,
  video.channel_id,
  video.channel_title,
  video.title,
  video.description,
  video.thumbnail_url,
  video.duration_iso8601,
  video.duration_seconds,
  video.duration_display,
  video.published_at,
  video.youtube_url,
  video.tags,
  current_snapshot.rank,
  current_snapshot.view_count,
  current_snapshot.like_count,
  current_snapshot.comment_count,
  greatest(current_snapshot.view_count - coalesce(previous_snapshot.view_count, current_snapshot.view_count), 0) as view_delta,
  greatest(current_snapshot.like_count - coalesce(previous_snapshot.like_count, current_snapshot.like_count), 0) as like_delta,
  current_snapshot.snapshot_date,
  current_snapshot.collected_at
from current_snapshot
join public.youtube_keyword_master_videos video on video.video_id = current_snapshot.video_id
left join previous_snapshot
  on previous_snapshot.video_id = current_snapshot.video_id
 and previous_snapshot.category_key = current_snapshot.category_key;

create or replace view public.youtube_keyword_master_dashboard_summary
with (security_invoker = true)
as
select
  (select count(*) from public.youtube_keyword_master_trending_videos) as current_video_count,
  (select count(distinct snapshot_date) from public.youtube_keyword_master_video_snapshots) as snapshot_days,
  (select max(collected_at) from public.youtube_keyword_master_video_snapshots) as last_collected_at,
  (select count(*) from public.youtube_keyword_master_analysis_results) as analysis_count;

alter table public.youtube_keyword_master_videos enable row level security;
alter table public.youtube_keyword_master_video_snapshots enable row level security;
alter table public.youtube_keyword_master_analysis_results enable row level security;
alter table public.youtube_keyword_master_collection_runs enable row level security;

drop policy if exists youtube_keyword_master_videos_public_read on public.youtube_keyword_master_videos;
create policy youtube_keyword_master_videos_public_read
  on public.youtube_keyword_master_videos for select to anon, authenticated using (true);
drop policy if exists youtube_keyword_master_snapshots_public_read on public.youtube_keyword_master_video_snapshots;
create policy youtube_keyword_master_snapshots_public_read
  on public.youtube_keyword_master_video_snapshots for select to anon, authenticated using (true);
drop policy if exists youtube_keyword_master_analysis_public_read on public.youtube_keyword_master_analysis_results;
create policy youtube_keyword_master_analysis_public_read
  on public.youtube_keyword_master_analysis_results for select to anon, authenticated using (true);
drop policy if exists youtube_keyword_master_runs_public_read on public.youtube_keyword_master_collection_runs;
create policy youtube_keyword_master_runs_public_read
  on public.youtube_keyword_master_collection_runs for select to anon, authenticated using (true);

grant select on public.youtube_keyword_master_videos to anon, authenticated;
grant select on public.youtube_keyword_master_video_snapshots to anon, authenticated;
grant select on public.youtube_keyword_master_analysis_results to anon, authenticated;
grant select on public.youtube_keyword_master_collection_runs to anon, authenticated;
grant select on public.youtube_keyword_master_trending_videos to anon, authenticated;
grant select on public.youtube_keyword_master_dashboard_summary to anon, authenticated;
