-- 서비스 접근(로그인) 코드와 기기 바인딩.
-- 코드 값은 비밀이므로 anon/authenticated 읽기를 허용하지 않는다.
-- 검증은 오직 Edge Function(service role)에서만 수행한다.

create table if not exists public.youtube_keyword_master_access_codes (
  code text primary key check (code ~ '^[0-9]{6}$'),
  label text not null default '',
  max_devices smallint not null default 2 check (max_devices >= 1),
  is_active boolean not null default true,
  expires_at timestamptz,
  created_at timestamptz not null default now()
);

create table if not exists public.youtube_keyword_master_code_devices (
  id bigint generated by default as identity primary key,
  code text not null references public.youtube_keyword_master_access_codes(code) on delete cascade,
  device_id text not null,
  ip text,
  user_agent text,
  first_seen timestamptz not null default now(),
  last_seen timestamptz not null default now(),
  unique (code, device_id)
);

create index if not exists youtube_keyword_master_code_devices_code_idx
  on public.youtube_keyword_master_code_devices (code);

-- RLS를 켜고 어떤 정책도 만들지 않는다 → anon/authenticated는 접근 불가.
-- service role 키(Edge Function)만 RLS를 우회해 읽고 쓸 수 있다.
alter table public.youtube_keyword_master_access_codes enable row level security;
alter table public.youtube_keyword_master_code_devices enable row level security;

-- 코드 노출 방지를 위해 공개 롤 권한을 명시적으로 회수한다.
revoke all on public.youtube_keyword_master_access_codes from anon, authenticated;
revoke all on public.youtube_keyword_master_code_devices from anon, authenticated;

-- 코드 발급 예시 (Dashboard SQL Editor에서 실행):
--   insert into public.youtube_keyword_master_access_codes (code, label, max_devices)
--   values ('482913', '홍길동 고객', 2);
-- max_devices: 이 코드로 인증 가능한 브라우저(기기) 수. 초과 시 새 기기는 차단된다.
-- expires_at: 만료 일시(선택). null이면 무기한. is_active=false로 즉시 비활성화 가능.
